name:                hBlackJack
version:             0.1.0.0
github:              "kaznak/hBlackJack"
license:             BSD3
author:              "Kazutaka NAKAMURA"
maintainer:          "kaznak.at.work@gmail.com"
copyright:           "2018 Kazutaka NAKAMURA"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kaznak/hBlackJack#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- random
- random-shuffle

library:
  source-dirs: src

executables:
  hBlackJack-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hBlackJack

tests:
  hBlackJack-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hBlackJack
